### PR TITLE
lillian/252 fix eslint header error for card component

### LINKED ISSUE #252: Address ESlint errors in the file: ./components/Card/card.tsx
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Remove file from eslint ignore
- Open terminal
- execute terminal command `npx eslint ./components/Card/card.tsx`

## Existing errors:
- Line 1:1 
  -  Error: missing header  header/header

### PR DESCRIPTION
**Pull request by lillian-nguyen**
Addresses following eslint error in ./components/Card/card.tsx : 

- Line 1:1 - Missing header header/header 

Additional changes: 
- Destructure type imports from React
- Add JSDoc comments

closes #252

### CODE REVIEW

**Review by kepsteen — APPROVED** [review]
LGTM

**Review by kepsteen — DISMISSED** [review]
LGTM

File: components/Card/card.tsx [hunk 1]
```diff
@@ -1,3 +1,6 @@
+// Copyright (c) Gridiron Survivor.
+// Licensed under the MIT License.
+
 import * as React from 'react';
 
 import { cn } from '@/lib/utils';
```
Comment (shashilo) [inline components/Card/card.tsx:6]: JS Docs linter should've cause that this function needs to be documented. Can you check with @hdkassamali and @destocot how they got that setup.

**Review by shashilo — CHANGES_REQUESTED** [review]
@lillian-nguyen Please review my comment.

File: components/Card/card.tsx (hunk 1 above)
Comment (hdkassamali) [reply components/Card/card.tsx:6]: Screenshot 2025-04-14 at 3 10 26 PM

@shashilo @lillian-nguyen, I also only saw that header error.

Comment (hdkassamali) [reply components/Card/card.tsx:6]: #311 
I'm not entirely sure, but it seems like I had similar functions in the dialog component, where I didn't have to document my functions. 

For example: `Dialog Overlay` and `DialogContent` didn't cause any lint errors, but `DialogHeader` and `DialogFooter` did. The only difference I see between the header and footer functions is that I'm passing in `className and ...props` as parameters before I pass in the elements, instead of after. 

It seems like all of the functions in the `card.tsx` file pass in className and ...props after the elements, and maybe that's why there are no errors

**Review by kepsteen — APPROVED** [review]
LGTM

**Review by shashilo — APPROVED** [review]
