### PR TITLE
Will/246 address eslint errors in alert dialgoue

### LINKED ISSUE #246: Address ESlint errors in the file: ./components/AlertDialogue/AlertDialgoue.tsx
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Open terminal
- execute terminal command `npx eslint ./components/AlertDialogue/AlertDialgoue.tsx

## Existing errors:
- Line 1:1  
 - Error: missing header  header/header
- Line 18:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 33:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 48:27  
  - Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 51:42  
  - Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 62:27  
  - Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 65:42  
  - Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 79:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 91:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 104:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 116:6  
  - Error: 'className' is missing in props validation  react/prop-types

### PR DESCRIPTION
**Pull request by CooleyWC**
Addressed ESlint errors in alertDialgoue.tsx file:
- Added JSDoc for AlertDialogHeader
- Added JSDoc for AlertDialogFooter

Destructured type imports from React.

Closes #246

### CODE REVIEW

File: components/AlertDialogue/AlertDialgoue.tsx [hunk 1]
```diff
@@ -12,9 +15,10 @@ const AlertDialogTrigger = AlertDialogPrimitive.Trigger;
 
 const AlertDialogPortal = AlertDialogPrimitive.Portal;
 
-const AlertDialogOverlay = React.forwardRef<
-  React.ElementRef<typeof AlertDialogPrimitive.Overlay>,
-  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Overlay>
+
```
Comment (kepsteen) [inline components/AlertDialogue/AlertDialgoue.tsx:18]: Can you add JSDoc comments for the other components as well, including AlertDialogOverlay, AlertDialogContent, etc.

**Review by kepsteen — CHANGES_REQUESTED** [review]

File: components/AlertDialogue/AlertDialgoue.tsx (hunk 1 above)
Comment (CooleyWC) [reply components/AlertDialogue/AlertDialgoue.tsx]: Added the JSDoc comments to the remaining components. Let me know if there are any further changes necessary.

**Review by shashilo — APPROVED** [review]

**Review by kepsteen — APPROVED** [review]
LGTM. Nice work 👍
