### PR TITLE
khurram/fix-eslint-errors-warning-modal

### LINKED ISSUE #287: Address ESlint errors in the file: ./components/WarningModal/WarningModal.tsx
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Remove file from eslint ignore
- Open terminal
- execute terminal command `npx eslint ./components/WarningModal/WarningModal.tsx`

## Existing errors:
- Line 1:1  
  - Error: missing header  header/header
- Line 15:22
  -   Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 19:23
  -   Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 21:18
  -   Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 21:27
  -   Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 30:24
  -   Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 30:33
  -   Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type

### PR DESCRIPTION
**Pull request by destocot**
Closes #287 

### Before:
The following ESLint errors were present in `./components/WarningModal/WarningModal.tsx`

1. `Line 1:1` - Missing header (`header/header`)
2. `Line 15:22` - Missing JSDoc comment (`jsdoc/require-jsdoc`)
3. `Line 19:23` - Missing return type on function (`@typescript-eslint/explicit-function-return-type`)
4. `Line 21:18` - Missing JSDoc comment (`jsdoc/require-jsdoc`)
5. `Line 21:27` - Missing return type on function (`@typescript-eslint/explicit-function-return-type`)
6. `Line 30:24` - Missing JSDoc comment (`jsdoc/require-jsdoc`)
7. `Line 30:33` - Missing return type on function (`@typescript-eslint/explicit-function-return-type`)

### After:
- Removed `components/WarningModal/WarningModal.tsx` from `.eslintignore`
- Added the missing header (`header/header`)
- Added JSDoc comment at the function for props: `giftExchangeData`, `members`, and `updateGiftExchangeMembers`
- Specified return type for the function
- Added JSDoc comment for the function `signIn`
- Added JSDoc comment for the function `joinExchange`

### Summary:
This PR addresses the ESLint errors in the `WarningModal` component as part of the effort to expand type coverage.

### CODE REVIEW

File: components/WarningModal/WarningModal.tsx [hunk 1]
```diff
@@ -1,24 +1,41 @@
...
 'use client';
 import { GiftExchange } from '@/app/types/giftExchange';
 import { GiftExchangeMember } from '@/app/types/giftExchangeMember';
 import { Button } from '@/components/Button/button';
 import { LogIn } from 'lucide-react';
 import { signInWithGoogle } from '@/lib/utils';
 import { useAuthContext } from '@/context/AuthContextProvider';
+import { JSX } from 'react';
 
 interface WarningModalProps {
```
Comment (kepsteen) [inline components/WarningModal/WarningModal.tsx:13]: Can you move the interface `WarningModalProps` into its own file in the same directory and rename it to `IWarningModalProps`.

**Review by kepsteen — CHANGES_REQUESTED** [review]

**Review by kepsteen — APPROVED** [review]
LGTM

**Review by shashilo — APPROVED** [review]
