### PR TITLE
fix: Addressed eslint issues in GiftSuggestion interface

### LINKED ISSUE #243: Address ESlint errors in the file: ./app/types/giftSuggestion.ts
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Open terminal
- execute terminal command `npx eslint ./app/types/giftSuggestion.ts`

## Existing errors:
- Line  1:1 
  -  Error: missing header  header/header

### PR DESCRIPTION
**Pull request by suzuhe481**
Closes #243

Addressed ESLint errors.

## Fixes
- Added headers.

### CODE REVIEW

File: app/types/giftSuggestion.ts [hunk 1]
```diff
@@ -1,3 +1,17 @@
+// Copyright (c) Gridiron Survivor.
+// Licensed under the MIT License.
+
+/**
```
Comment (kepsteen) [inline app/types/giftSuggestion.ts:4]: No need for a jsdoc comment on an interface, we only use them for functions

**Review by kepsteen — CHANGES_REQUESTED** [review]

File: app/types/giftSuggestion.ts (hunk 1 above)
Comment (suzuhe481) [reply app/types/giftSuggestion.ts]: Removed the jsdoc.
