### PR TITLE
Haydn/250 address eslint error button

### LINKED ISSUE #250: Address ESlint errors in the file: ./components/Button/button.tsx
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Open terminal
- execute terminal command `npx eslint ./components/Button/button.tsx`

## Existing errors:
- Line 1:1 
  -  Error: missing header  header/header

### PR DESCRIPTION
**Pull request by haydnkerr**
fix #250 

Add header to button.tsx to resolve ESlint error

Included JSDoc comment for button

### CODE REVIEW

**Review by kepsteen — CHANGES_REQUESTED** [review]
Can you add a JSDoc comment for the button? If you look through the other PRs you should be able to find examples for the other components

**Comment by haydnkerr** [comment]
@kepsteen I may have to create another PR. I've made those changes but my branch is so tangled it won't let update the PR

**Review by shashilo — DISMISSED** [review]

**Review by kepsteen — APPROVED** [review]
LGTM

File: components/Button/button.tsx [hunk 1]
```diff
@@ -1,9 +1,22 @@
...
+/**
+ * A customizable Button Component.
+ * @param {object} props - Props for the button.
+ * @param {string} props.className - Additional CSS classes
+ * @param {string} [props.variant="default"] - CSS styling of button such as color, border, drop shadow ("defauly", "destructive", "outline", "secondary", "ghost", "link")
+ * @param {string} [props.size="default"] - Size of button ("default", "sm", "m", "lg", "icon")
+ * @param {boolean} [props.asChild="false"] - Renders as child component if true
+ * @returns {Button} - returns Button component.
+ */
+
```
Comment (nickytonline) [inline components/Button/button.tsx:19]: refactor (blocking): The comments currently don't appear if you hover over a button because they are not above the Button component in the file. This is what it currently looks like if you hover over a Button component.

CleanShot 2025-05-09 at 07 51 12@2x

and this is what it looks like if you move the JSDoc comments just above the Button component, i.e.

```tsx
/**
 * A customizable Button Component.
 * @param {object} props - Props for the button.
 * @param {string} props.className - Additional CSS classes
 * @param {string} [props.variant="default"] - CSS styling of button such as color, border, drop shadow ("defauly", "destructive", "outline", "secondary", "ghost", "link")
 * @param {string} [props.size="default"] - Size of button ("default", "sm", "m", "lg", "icon")
 * @param {boolean} [props.asChild="false"] - Renders as child component if true
 * @returns {Button} - returns Button component.
 */
const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
```
CleanShot 2025-05-09 at 07 50 56@2x

**Review by nickytonline — CHANGES_REQUESTED** [review]

File: components/Button/button.tsx (hunk 1 above)
Comment (haydnkerr) [reply components/Button/button.tsx:19]: Ok thank you! I'll update this asap

**Review by nickytonline — APPROVED** [review]
:shipit:

**Review by kepsteen — APPROVED** [review]

**Comment by alexappleget** [comment]
Test comment
