### PR TITLE
fix: eslint errors for badge component

### LINKED ISSUE #249: Address ESlint errors in the file: ./components/Badge/badge.tsx
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Open terminal
- execute terminal command `npx eslint ./components/Badge/badge.tsx

## Existing errors:
- Line 1:1  
  - Error: missing header  header/header
- Line 29:1  
  - Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 29:1  
  - Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 29:1  
  - Error: Function component is not an arrow function  react/function-component-definition

### PR DESCRIPTION
**Pull request by destocot**
Closes #249 

### Before:
The following errors were present in `./components/Badge/badge.tsx`:

1. `Line 1:1` - Missing header `header/header`
2. `Line 29:1` - Missing JSDoc comment. (`jsdoc/require-jsdoc`)
3. `Line 29:1` - Missing return type on function. (`@typescript-eslint/explicit-function-return-type`)
4. `Line 29:1` - Function component is not an arrow function. (`react/function-component-definition`)

### After:
- Removed `components/Badge/badge.tsx` from `.eslint.ignore`
- Added the missing header `header/header`.
- Added JSDoc comment at the function.
- Specified return type for the function.
- Refactored the function to use an arrow function.

### Summary:
This PR addresses the eslint errors found in the `Badge` component.

### CODE REVIEW

File: components/Badge/badge.tsx [hunk 1]
```diff
@@ -26,10 +30,17 @@ export interface BadgeProps
   extends React.HTMLAttributes<HTMLDivElement>,
     VariantProps<typeof badgeVariants> {}
 
-function Badge({ className, variant, ...props }: BadgeProps) {
+/**
```
Comment (alexappleget) [inline components/Badge/badge.tsx:33]: For the way we define things, use this example as guidance for this:

```
/**
 * Alert Notification pop ups.
 * @param props - The page props.
 * @param props.message - Custom message to add into notification.
 * @param props.variant - Different variants for the notification.
 * @returns {JSX.Element} The rendered weekly picks page.
 */
const Alert = ({
  message,
  variant = AlertVariants.Default,
}: IAlertNotification): JSX.Element => {
```

File: components/Badge/badge.tsx [hunk 2]
```diff
@@ -1,5 +1,9 @@
+// Copyright (c) Gridiron Survivor.
+// Licensed under the MIT License.
+
 import * as React from 'react';
```
Comment (alexappleget) [inline components/Badge/badge.tsx:4]: Nit: I know it's not part of the ticket but could you delete this line? It's not needed in this file and we don't want all these things being imported into a single file.

File: components/Badge/badge.tsx [hunk 3]
```diff
@@ -1,5 +1,9 @@
...
 import { cva, type VariantProps } from 'class-variance-authority';
+import type { JSX } from 'react';
```
Comment (alexappleget) [inline components/Badge/badge.tsx:6]: Nit: Delete 'type' and just leave it as 'import {JSX} from 'react';'

File: components/Badge/badge.tsx [hunk 4]
```diff
@@ -23,13 +26,20 @@ const badgeVariants = cva(
...
 
 export interface BadgeProps
-  extends React.HTMLAttributes<HTMLDivElement>,
+  extends HTMLAttributes<HTMLDivElement>,
     VariantProps<typeof badgeVariants> {}
 
-function Badge({ className, variant, ...props }: BadgeProps) {
+/**
+ * Badge component.
+ * @param props - The badge props.
```
Comment (shashilo) [inline components/Badge/badge.tsx:34]: Let's do it where we add the type into the comment as well. Might need to update JS Docs config for this to fail the linter.
image

**Review by shashilo — CHANGES_REQUESTED** [review]
Please review my comment.

**Review by kepsteen — DISMISSED** [review]
LGTM

**Review by shashilo — APPROVED** [review]

**Review by alexappleget — APPROVED** [review]
