### PR TITLE
Lillian/253 fix eslint errors command component

### LINKED ISSUE #253: Address ESlint errors in the file: ./components/Command/command.tsx
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Remove file from eslint ignore
- Open terminal
- execute terminal command `npx eslint ./components/Command/command.tsxv`

## Existing errors:
- Line 1:1 
  -  Error: missing header  header/header
- Line 14:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 26:23 
  -  Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 26:61 
  -  Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 41:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 42:52  
  - Error: Unknown property 'cmdk-input-wrapper' found  react/no-unknown-property
- Line 60:6 
  -  Error: 'className' is missing in props validation  react/prop-types
- Line 86:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 102:6 
  -  Error: 'className' is missing in props validation  react/prop-types
- Line 114:6  
  - Error: 'className' is missing in props validation  react/prop-types
- Line 127:25  
  - Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 130:43 
  -  Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type

### PR DESCRIPTION
**Pull request by lillian-nguyen**
Addresses following ESLint errors in./components/Command/command.tsx: 

- Line 1:1
  - Error: missing header header/header
- Line 14:6
  - Error: 'className' is missing in props validation react/prop-types
- Line 26:23
  - Error: Missing JSDoc comment. jsdoc/require-jsdoc
- Line 26:61
  - Error: Missing return type on function. @typescript-eslint/explicit-function-return-type
- Line 41:6
  - Error: 'className' is missing in props validation react/prop-types
- Line 42:52
  - Error: Unknown property 'cmdk-input-wrapper' found react/no-unknown-property
- Line 60:6
  - Error: 'className' is missing in props validation react/prop-types
- Line 86:6
  - Error: 'className' is missing in props validation react/prop-types
- Line 102:6
  - Error: 'className' is missing in props validation react/prop-types
- Line 114:6
  - Error: 'className' is missing in props validation react/prop-types
- Line 127:25
  - Error: Missing JSDoc comment. jsdoc/require-jsdoc
- Line 130:43
  - Error: Missing return type on function. @typescript-eslint/explicit-function-return-type

Changes Implemented: 
- Added missing `header/header`
- Added JSDoc comments for functions 
- Included return type for function 
- Destructured type imports from React
- Previously missing className errors were not seen with ESLint

closes #253

### CODE REVIEW

**Review by kepsteen — CHANGES_REQUESTED** [review]
It looks like you're having some build issues. Can you try running the command `pnpm run build` and see what errors you're getting?

**Comment by lillian-nguyen** [comment]
> It looks like you're having some build issues. Can you try running the command `pnpm run build` and see what errors you're getting?

Yep! This is what i'm seeing on my end
Screenshot 2025-04-22 at 11 49 36 AM

File: components/Command/command.tsx [hunk 1]
```diff
@@ -35,11 +49,17 @@ const CommandDialog = ({ children, ...props }: DialogProps) => {
...
+ * @param {ComponentPropsWithoutRef<typeof CommandPrimitive.Input>} props - Props passed to the CommandPrimitive.Input component.
+ * @param {string} [props.className] - Additional class names for styling. 
+ * @returns {JSX.Element} Rendered input container. 
+ */
+const CommandInput = forwardRef<
+  ElementRef<typeof CommandPrimitive.Input>,
+  ComponentPropsWithoutRef<typeof CommandPrimitive.Input>
 >(({ className, ...props }, ref) => (
-  <div className="flex items-center border-b px-3" cmdk-input-wrapper="">
+  <div className="flex items-center border-b px-3" {...{ "cmdk-input-wrapper":"" }}>
```
Comment (mathematiCode) [inline components/Command/command.tsx:62]: Do you know how/why this fixes the error? I did find someone else with the same issue/solution here https://github.com/shadcn-ui/ui/issues/3366 but I'm not understanding why that fixes the issue.

Comment (lillian-nguyen) [reply components/Command/command.tsx:62]: From my understanding, React doesn't recognize cmdk-input-wrapper as a standard attribute or prop in JSX so an error is thrown when it's used directly. Using the spread operator to pass the attribute as an object key works because cmdk-input-wrapper isn't interpreted as a React prop anymore - it's passed directly to the DOM element.

**Review by mathematiCode — APPROVED** [review]
It looks good to me as long as you get the build working like Cody mentioned and merge the latest changes. 
I had to do a little digging to figure out how you were addressing the 'className' is missing in props validation error so in the future maybe you could include how you addressed the errors in your PR description for the less obvious fixes.

File: components/Command/command.tsx [hunk 2]
```diff
@@ -67,9 +93,15 @@ const CommandList = React.forwardRef<
...
 CommandList.displayName = CommandPrimitive.List.displayName;
 
-const CommandEmpty = React.forwardRef<
-  React.ElementRef<typeof CommandPrimitive.Empty>,
-  React.ComponentPropsWithoutRef<typeof CommandPrimitive.Empty>
+/**
+ * Component that displays a message when the command list has no matching results. 
+ * @param {ComponentPropsWithoutRef<typeof CommandPrimitive.Empty>} props - Props passed to CommandPrimitive.Empty.
+ * @param {string} [props.className] - Additional class names for styling.
+ * @returns {JSX.Element} Renders empty state element.
```
Comment (mathematiCode) [inline components/Command/command.tsx:100]: If this displays a message when there are no matching results, what does it mean that it renders an empty state element? Is that only in the case when there are matching results? I'm just a little unclear on what the returns description means.

**Comment by lillian-nguyen** [comment]
> It looks good to me as long as you get the build working like Cody mentioned and merge the latest changes. I had to do a little digging to figure out how you were addressing the 'className' is missing in props validation error so in the future maybe you could include how you addressed the errors in your PR description for the less obvious fixes.

That's a great point, and I'll make the edits! Thank you, Julianna!

File: components/Command/command.tsx (hunk 2 above)
Comment (lillian-nguyen) [reply components/Command/command.tsx:100]: If there are no matching results, the CommandEmpty component is rendered along with an element (maybe a message) indicating that there were no matches found. And this situation is reflective of an empty state element. If there were results then the matching items would be listed instead.

Comment (mathematiCode) [reply components/Command/command.tsx:100]: Makes sense thanks!

**Review by kepsteen — APPROVED** [review]

**Review by shashilo — APPROVED** [review]
