### PR TITLE
fix: address eslint errors in Completed Exchange Card component

### LINKED ISSUE #254: Address ESlint errors in the file: ./components/CompletedExchangeCard/CompletedExchangeCard.tsx
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Remove file from eslint ignore
- Open terminal
- execute terminal command `npx eslint ./components/CompletedExchangeCard/CompletedExchangeCard.tsx`

## Existing errors:
- Line 1:1  
  - Error: missing header  header/header
- Line 18:38 
  -  Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 20:32  
  - Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 27:15 
  -  Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 46:23 
  -  Error: Do not use Array index in keys  react/no-array-index-key

### PR DESCRIPTION
**Pull request by hdkassamali**
Addresses the following eslint errors in the Completed Exchange Card Component:

- Line 1:1
  - Error: missing header header/header
- Line 18:38
  - Error: Missing JSDoc comment. jsdoc/require-jsdoc
- Line 20:32
  - Error: Missing return type on function. @typescript-eslint/explicit-function-return-type
- Line 27:15
  - Error: Missing return type on function. @typescript-eslint/explicit-function-return-type
- Line 46:23
  - Error: Do not use Array index in keys react/no-array-index-key

closes #254

### CODE REVIEW

File: .eslintignore [hunk 1]
```diff
@@ -1,4 +1,4 @@
-# Ignored files due to ESLINT errors
+// # Ignored files due to ESLINT errors
```
Comment (alexappleget) [inline .eslintignore:1]: Delete this change. Sorry I forgot to mention this.

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx [hunk 2]
```diff
@@ -1,6 +1,9 @@
+// Copyright (c) Gridiron Survivor.
+// Licensed under the MIT License.
+
 'use client';
 
-import { useEffect, useState } from 'react';
+import React, { useEffect, useState } from 'react';
```
Comment (alexappleget) [inline components/CompletedExchangeCard/CompletedExchangeCard.tsx:6]: Sorry about having you do this. Turns out we are going to be doing a different preference for this.

Delete 'React, ' and then add ', JSX' right after useState

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx [hunk 3]
```diff
@@ -15,16 +18,31 @@ interface CompletedExchangeCardProps {
...
+/**
+ * Function that shows up after gift exchange completes and shows confetti.
+ * @param props - Props for function
+ * @param props.members - Gift exchange members.
+ * @returns The rendered card component with confetti animation.
+ */
 export const CompletedExchangeCard = ({
   members,
-}: CompletedExchangeCardProps) => {
+}: CompletedExchangeCardProps): React.JSX.Element => {
```
Comment (alexappleget) [inline components/CompletedExchangeCard/CompletedExchangeCard.tsx:29]: And then delete 'React.' Here and just leave it as 'JSX.Element'

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx [hunk 4]
```diff
@@ -42,8 +60,8 @@ export const CompletedExchangeCard = ({
       </CardHeader>
       <CardContent>
         <div className="space-y-4">
-          {members.map((member, index) => (
-            <div key={index} className="grid grid-cols-[auto_1fr_auto]">
+          {members.map((member) => (
+            <div key={member.id} className="grid grid-cols-[auto_1fr_auto]">
```
Comment (shashilo) [inline components/CompletedExchangeCard/CompletedExchangeCard.tsx:64]: Why was this updated? It should only be ES Lint changes.

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx [hunk 5]
```diff
@@ -15,16 +18,31 @@ interface CompletedExchangeCardProps {
...
-    const timer = setTimeout(() => {
-      setShowConfetti(false);
-    }, 1000);
 
-    return () => clearTimeout(timer);
+  /**
+   * Function that triggers the confetti.
+   * @returns {Promise<void>} - A promise that resolves after confetti is turned off.
+   */
+  const triggerConfetti = (): Promise<void> => {
```
Comment (shashilo) [inline components/CompletedExchangeCard/CompletedExchangeCard.tsx:36]: Why is this new functionality here?

**Review by shashilo — CHANGES_REQUESTED** [review]

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx (hunk 4 above)
Comment (alexappleget) [reply components/CompletedExchangeCard/CompletedExchangeCard.tsx:64]: It was an eslint error. Before it was just 'index' and eslint didn't like it

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx (hunk 5 above)
Comment (alexappleget) [reply components/CompletedExchangeCard/CompletedExchangeCard.tsx:36]: To handle the eslint error for it I had him move it outside of the useEffect to define it. Then had him call the function inside the useEffect like how we did it in gridiron survivor

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx (hunk 4 above)
Comment (hdkassamali) [reply components/CompletedExchangeCard/CompletedExchangeCard.tsx:64]: 64:23  error  Do not use Array index in keys  react/no-array-index-key

this is the error I got before we made the change

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx [hunk 6]
```diff
@@ -15,16 +18,31 @@ interface CompletedExchangeCardProps {
   members: GiftExchangeMember[];
 }
 
+/**
+ * Function that shows up after gift exchange completes and shows confetti.
+ * @param props - Props for function
```
Comment (shashilo) [inline components/CompletedExchangeCard/CompletedExchangeCard.tsx:23]: Same here. Add type into the comment.
image

**Review by shashilo — CHANGES_REQUESTED** [review]

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx (hunk 6 above)
Comment (hdkassamali) [reply components/CompletedExchangeCard/CompletedExchangeCard.tsx:23]: should I add type for all 3 or just the first @param props? 
``` 
@param props - Props for function
@param props.members - Gift exchange members.
@returns The rendered card component with confetti animation.
```

**Review by kepsteen — DISMISSED** [review]
LGTM

File: components/CompletedExchangeCard/CompletedExchangeCard.tsx (hunk 6 above)
Comment (shashilo) [reply components/CompletedExchangeCard/CompletedExchangeCard.tsx]: All 3

**Review by shashilo — APPROVED** [review]

**Review by shashilo — APPROVED** [review]

**Review by alexappleget — APPROVED** [review]
