### PR TITLE
Hector/290 fix: address eslint issues in generateAndUpdateNewGiftSuggestion.ts

### LINKED ISSUE #290: Address ESlint errors in the file: ./lib/generateAndUpdateNewGiftSuggestion.ts
# Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Remove file from eslint ignore
- Open terminal
- execute terminal command `npx eslint ./lib/generateAndUpdateNewGiftSuggestion.ts`

## Existing errors:
- Line 1:1 
  -  Error: missing header  header/header
- Line 8:8 
  -  Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 8:8
  -   Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 29:1
  -   Error: Expected indentation of 2 spaces but found 6.  indent
- Line 30:1 
  -  Error: Expected indentation of 0 spaces but found 4.  indent
- Line 42:1
  -   Error: Expected indentation of 4 spaces but found 6.  indent
- Line 43:1
  -   Error: Expected indentation of 6 spaces but found 8.  indent
- Line 51:1
  -   Error: Expected indentation of 4 spaces but found 6.  indent
- Line 52:1
  -   Error: Expected indentation of 4 spaces but found 6.  indent

### PR DESCRIPTION
**Pull request by suzuhe481**
Closes #290

Addressed ESLint errors.

## Fixes
- Added headers.
- Added JSDocs.
- Added missing return type to generateAndUpdateNewGiftSuggestion function.
- Addressed indenting errors.
  - Indenting errors were inside the template literal prompt used for AI generation. I had to refactor some lines to comply with eslint rules, and extract some logic to store in variables to use.

## Notes
- I had to refactor the prompt used for AI generation, but the prompt's value should still be the same.

### CODE REVIEW

File: lib/generateAndUpdateNewGiftSuggestion.ts [hunk 1]
```diff
@@ -1,22 +1,47 @@
...
 import { Profile } from '@/app/types/profile';
 import { createClient } from './supabase/server';
 import { getAmazonImage } from './getAmazonImage';
 
+/**
+ *
+ * Function to generate a gift suggestion, and update the gift suggestion with the generated suggestion
+ * @param allGiftSuggestions - List of gift suggestions.
+ * @param budget - Gift budget.
+ * @param feedback - Feedback for new gift suggestion.
```
Comment (kepsteen) [inline lib/generateAndUpdateNewGiftSuggestion.ts:16]: can you add the types of each param to the jsdoc?

**Review by kepsteen — CHANGES_REQUESTED** [review]
One small fix, otherwise looks good to me

File: lib/generateAndUpdateNewGiftSuggestion.ts (hunk 1 above)
Comment (suzuhe481) [reply lib/generateAndUpdateNewGiftSuggestion.ts]: Added the missing param types.

**Review by kepsteen — APPROVED** [review]

File: lib/generateAndUpdateNewGiftSuggestion.ts [hunk 2]
```diff
@@ -1,22 +1,47 @@
...
   feedback: string,
   gift: GiftSuggestion,
   recipient: Profile | null,
-) {
+): Promise<GiftSuggestion> {
   if (!recipient) {
     throw new Error('Recipient profile is missing');
   }
 
   try {
```
Comment (nickytonline) [inline lib/generateAndUpdateNewGiftSuggestion.ts:32]: refactor (nit): I would have left this inline.

**Review by nickytonline — APPROVED** [review]
:shipit:

File: lib/generateAndUpdateNewGiftSuggestion.ts (hunk 2 above)
Comment (suzuhe481) [reply lib/generateAndUpdateNewGiftSuggestion.ts:32]: Do you mean to move the return type to the same line as the recipient parameter like this
```recipient: Profile | null,): Promise<GiftSuggestion> {```
 or something else? 
The formatter we use doesn't give me a lot of ways to adjust how the parameters and return type are laid out. If I try that, it gets formatted to how I originally had it.

Comment (nickytonline) [reply lib/generateAndUpdateNewGiftSuggestion.ts:32]: I meant this could have stayed inline.

```
allGiftSuggestions
      .map((suggestion, index) => {
        return `Gift ${index + 1}: 
          - Title: ${suggestion.title}
          - Price: $${suggestion.price}
          - Description: ${suggestion.description}
          - Match Score: ${suggestion.matchScore}
          - Match Reasons: ${suggestion.matchReasons.join(', ')}
          `;
      })
      .join('\n')
```

Comment (suzuhe481) [reply lib/generateAndUpdateNewGiftSuggestion.ts:32]: Ah ok. That's how it was originally, but since it was a template literal, the indenting would always move when it gets formatted on save, so the eslint error remained. So I had to extract that mapping logic and store it in ```formattedGiftSuggestions```.

This is what happened after saving.
image
