### PR TITLE
will/285-address-eslint-errors-in-snowOverlayWrapper

### LINKED ISSUE #285: Address ESlint errors in the file: ./components/SnowOverlayWrapper/SnowOverlayWrapper.tsx
## Replicating errors:
- Open repo in VSCode ( or editor of choice)
- Remove file from eslint ignore
- Open terminal
- execute terminal command `npx eslint ./components/SnowOverlayWrapper/SnowOverlayWrapper.tsx`

## Existing errors:
- Line 1:1  
  - Error: missing header  header/header
- Line 6:16
  -   Error: Missing JSDoc comment.  jsdoc/require-jsdoc
- Line 6:16
  -   Error: Missing return type on function.  @typescript-eslint/explicit-function-return-type
- Line 6:16 
  -  Error: Function component is not an arrow function  react/function-component-definition

### PR DESCRIPTION
**Pull request by CooleyWC**
- Add JSdoc comments. 
- Add header. 
- Add missing return type. 
- Import JSX from react.
- Change function declaration to arrow function expression. 
- Describe context variable and disabled prop.

Closes #285

### CODE REVIEW

File: components/SnowOverlayWrapper/SnowOverlayWrapper.tsx [hunk 1]
```diff
@@ -1,9 +1,22 @@
...
+// Licensed under the MIT License.
+
 'use client';
 
+import { JSX } from 'react';
 import { useSnowOverlay } from '@/providers/SnowOverlayProvider';
 import { SnowOverlay } from 'react-snow-overlay';
 
-export default function SnowOverlayWrapper() {
+/**
```
Comment (alexappleget) [inline components/SnowOverlayWrapper/SnowOverlayWrapper.tsx:10]: So for components that don't have props, you just have to write a brief description of what it does and what it returns for JSDoc comments

**Review by alexappleget — CHANGES_REQUESTED** [review]

File: components/SnowOverlayWrapper/SnowOverlayWrapper.tsx (hunk 1 above)
Comment (CooleyWC) [reply components/SnowOverlayWrapper/SnowOverlayWrapper.tsx:10]: new commit - I simplified the JSDoc comments as requested.

**Review by alexappleget — APPROVED** [review]

**Review by alexappleget — DISMISSED** [review]

**Review by shashilo — DISMISSED** [review]

**Review by shashilo — APPROVED** [review]
